COMPILE_DEPS = CORE_DEPS + KRYO + CLI

osgi_jar_with_tests(
    karaf_command_packages = ["org.onosproject.learningswitch"],
    deps = COMPILE_DEPS,
)

onos_app(
    category = "learning switch",
    description = "Provisions traffic between end-stations using hop-by-hop flow programming by",
    title = "ONOS sucks",
    url = "http://onosproject.org",
)
